## Main Hyprland config ## 

# Source the rest of the files required from here
source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/programs.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/decorations.conf
source = ~/.config/hypr/layout.conf
source = ~/.config/hypr/misc.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/animations.conf

